# Thanks Freek
# https://github.com/spatie/laravel-backup/blob/87d332c/.github/workflows/run-tests.yml
name: run-tests

on: [push]

jobs:
    tests:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: true
            matrix:
                php: [7.2, 7.3, 7.4]

        name: PHP${{ matrix.php }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v1

            -   name: Setup PHP
                uses: shivammathur/setup-php@v1
                with:
                    php-version: ${{ matrix.php }}
                    extensions: curl, mbstring, zip
                    coverage: none

            -   name: Install dependencies
                run: composer update --prefer-dist --no-interaction --no-suggest

            -   name: Execute tests
                run: vendor/bin/phpunit

            -   name: Execute style check
                run: vendor/bin/php-cs-fixer fix --dry-run --diff
